setup/startup: ensure recent pip; ignore VCS URIs in check_requirements()
Summary:
This will hopefully fix this exception when deploying under Debian
wheezy:

    Traceback (most recent call last):
      File "/srv/inbox/bin/inbox-start", line 70, in <module>
        main()
      File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 488, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 474, in main
        self.invoke(ctx)
      File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 659, in invoke
        ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 325, in invoke
        return callback(*args, **kwargs)
      File "/srv/inbox/bin/inbox-start", line 43, in main
        preflight()
      File "/srv/inbox/inbox/util/startup.py", line 133, in preflight
        check_requirements(requirements_path)
      File "/srv/inbox/inbox/util/startup.py", line 32, in check_requirements
        require(x)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 603, in resolve
        requirements = list(requirements)[::-1]
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 2717, in parse_requirements
        "version spec")
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 2682, in scan_list
        raise ValueError(msg, line, "at", line[p:])
    ValueError: ('Expected version spec in', 'git+https://github.com/inboxapp/zerorpc-python.git@master#egg=zerorpc', 'at', '+https://github.com/inboxapp/zerorpc-python.git@master#egg=zerorpc')

Test Plan:
Manually check that bin/inbox-start works either in my dev VM, or we'll just
test it in staging before we deploy.

Reviewers: spang, charles

Differential Revision: https://review.inboxapp.com/D403